# Testing doc for Mad Data Proj

In [ ]:
import googlemaps
import os
import time
import requests
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
import re
import matplotlib.pyplot as plt
from better_profanity import profanity
load_dotenv()

True

In [3]:
maps_client = googlemaps.Client(key = os.getenv('google_maps_api_key'))

In [4]:
maps_client.places("food on state street, madison wisconsin", type = ['resturaunt'], page_token='ATCDNfWTuQqERLyaAMyPBxPKrj_028LEBzgJb4KWoESdXYC85jig_3z2e4mvqtuBslY6ziviPrtCNm-TdVZAqUKJ_4Ewpbu2TndJK74PZGhC388bVLpdYZq8ajZMNsdYVe-dKzmudcVm78KJX27fLbusCMHsbd59LffVgITONUc6mSrmHOgxosmLMCAxr1voKaRdOZbneT-liKz3ziFKumZK2Zf2Qaykxi6_1NL-vlYywEfQI_VXk7Jn4ZWFZZRijxz5yIhmfwk-q6ooTBPucfMBGyqU3o609vUzOudDQLFW47wZbdm6GIQa31thsNP7dO6FHcow-7hRIlH1Bp9dqlFFvZEoUFlCYerD2VgoyYXYsRwHJutU2wP1bf-zZrL5veYPAqnso1o4RVWaflSaEFdgSAu4qrT1YWulIyxphcw8ithcSmUMXiSuLy0q8qssPw')

{'html_attributions': [],
 'next_page_token': 'ATCDNfUX_ieN7LsZfy4U_YdNaZy8BTTWWfewHAN3VPxtycsbql__x56OHpVhOR-BANAkBiZmky_F2v-5pthCkMM_UjwCh5uvlN-6zAmY9GX-39Cq1AnMta09Bd97fSIdShefrVJjEDvgU4O5TJDPeYTYvbfW64tdXxOGKBdZ_WBqTFgc_EPMOMeEtHDkLi-ATcgEzVnBrZi0KWWtjjZSpQUr7Ms6N9j9FTLv8cwBlfSAxQP2F5Ve5YKxiKPq4PGI76ab2cRRybda3AEwCylMbM65rKtZ2-hUeX7CKJ4jYoC-iCssnkUClIQAecvRbw1VjNAChQY5kbQIX4YLTlid-yMG7EQus2EL5towSk_X3VsyMlVg2bmUfiVkrGfq8XGPKpZ3GTEav0fPzFGzSGOJs-I-KKSuDoyjVmqgP-tC3Y6Sz-Rw0cF8r3sBG5KnkFJcwsOhK0J__0y7RXkFbMRQ-A60wAawFuoJ3sg-zkL5rhOeTd4Akbtyq1xBWq07yx_1oT_6PBC9vXfoRdqmTXur8xpS9cyO72PKgg7Dy_yG5pkL9uhKr3MGSbVj8-1_lfqD9HDGagGsfMY3vYcQxL4lv3tBet9-Hiu2mL7KFaJque23jIxcLVbw6RPQPH6DDzqz2rKj6mFlvN_4GB0G12mEHtY',
 'results': [{'business_status': 'OPERATIONAL',
   'formatted_address': '449 State St Suite E, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.07458039999999, 'lng': -89.3934415},
    'viewport': {'northeast': {'lat': 43.07595182989271,
      'lng': -89.39195892010727},
     'southwest': {'lat': 43.07325217010727, 'lng': -89.39465857989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Asian Kitchen',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107715013792077077951">Aron Szucs</a>'],
     'photo_reference': 'ATCDNfUjHnDhcohTYR2JihkJaos7Y1sknOCU7scjVNPZUZ832oZGJgzW1uVMnDoiiPvdR9Rlaw83Hjlbo30YtM1QxQ7eULxvuWBoUjClE3BW9tHfGsETVWizpqFCEfhxbsp2OZ1QttceXhe8iynkam9k7ylFe2URL5oqFGfYwviEkCnyWU7LZh0ZMUOlJlAuxceiBGCuQ14vM1er_S-NExM5Q8UKvPciYuNI4Yi0TRxSQWuXG1NYPhHmpMlXXD_aChu36nDfkdtohBX_BykxibQa6V3-0vV-ad5Fpq1d_CL_mCETk8IFPJXqkxMSl8WUu4hzfD0sW4X2X4U3q07ICNP9oxUYujCKsjn2Dj6jkP5PqIgn4-e33VKGqpHJI0f4LtbtvG2t4PzbdsE9xh4jslXI52XlVIpsHPebH1uDzeakNXXZuqOTTlgmHQ9FiWESiDlUtfLM57dj7BYBGIN36L4cKtf3US0JdhmOqUR-nWUSQL3omRz9iU2aD9-YEoTLZVKl8JzvefOXvmPXdfeXYgTIq9vwW9vLCe4IQEPEvxDDVZIlqpVudF2p-GjTbDCF4wjX2Y52radb',
     'width': 3000}],
   'place_id': 'ChIJYfFUh25TBogRadcybS45CEk',
   'price_level': 1,
   'rating': 2.5,
   'reference': 'ChIJYfFUh25TBogRadcybS45CEk',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 66},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '232 State Street At Johnson, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0749274, 'lng': -89.38953269999999},
    'viewport': {'northeast': {'lat': 43.07629462989272,
      'lng': -89.38825627010726},
     'southwest': {'lat': 43.07359497010728, 'lng': -89.39095592989271}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Noodles and Company',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4618,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109528282699144383101">Edu Peron</a>'],
     'photo_reference': 'ATCDNfUL28iLD7tcJPQeZg-Xa7XOHMio2Z0NfFbbXiV4R0_-m3SJvlz_dQneF8cvQBYNKCCVnmQqK_vw6RWb-rBg8nY-kLHxpi1zXbkBT6sJJb2odjDedGBOjZnJIRq8m-4kPvgsnAwVxGnd1LRMcZKLCZu98YYvF7P7g7ZEN9woReqaoqLLrzYoXl2dPCDiMEwvSf54c-qaq9qQuwRGeD5UKINe6BUQOUHBuhzGnfYmGy3U51RjbLQSOmYcwS6OGbn2UTTiW6-HOiSkDd9cn11ATkLKYy1FPBwgycujK1_hU0a6Jx3C71xT_GtKEqn0pS1mc07k9KynaPVKq-0fkSgVH9FzFKfwMfJcr4pobpTeFpo74of3e3SbSxQLpAU-0-FbDIqUE7eHADAh6sYoRWfncjClD8KI35Dpk0MVGJT2eW9sxtkpaXzMDYi7Oa0kPn3CYy03Co7MOnHVbKNCeZVNnYLtdYBuiN9xqLKkKRl4zQOdH7Tv2i-KfhAccMiLDspWnFHkrU2Iwm06MgI4BT46_WeVcROAvPSdwe4WTeehNeg8LWbmY2YNY4sJMPAMDKkp2aUbigZFd3JzVA',
     'width': 3464}],
   'place_id': 'ChIJCa81jTdTBogRmcaEF_I9ta0',
   'price_level': 1,
   'rating': 3.8,
   'reference': 'ChIJCa81jTdTBogRmcaEF_I9ta0',
   'types': ['restaurant',
    'meal_takeaway',
    'store',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 688},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '579 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0747492, 'lng': -89.395242},
    'viewport': {'northeast': {'lat': 43.07616232989272,
      'lng': -89.39392267010727},
     'southwest': {'lat': 43.07346267010728, 'lng': -89.39662232989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': "Raising Cane's Chicken Fingers",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1500,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114383601041604411388">Raising Cane&#39;s Chicken Fingers</a>'],
     'photo_reference': 'ATCDNfUDspBeGa6eDaoQ1QB8H6yIBtNGG0qfMgJWv8nYfXaoPnP0X61ffGpxGfo0NRkVEdTg08O7W48f5z5R-JmD9vE_IRpH0Igi8AT2m2t2lPStYt5DMKNj6NauZ7k0bTOdPQindLZRpaRIZAv0S5m0up4ejI1fQwRsncKYIGOB0w7ffdStgHjAtLijV-D7kj9ELKw7A9EIl6G1aNFLONKg2JgAeXMArplLLZOBSDNmQzUr_Tyh6U-Cyqt3u2EfbkIcPqoDYMHMngJonyefggCWhiAgcedi6QGKr2HD_M5_TIBFBpR41LAS2rl0B7u9sTjV-zf-kqIK8YNJE2EwAcA8W0UbB1whqkQwJf11osCumIONDbhhRHXlIybXh5iOIA6gtmO61996VUaPKNXWY6vLbp6F1pF21cIYK4CTWkrt0YU0-2lwJQ6So7uguTptttf1qgBvr4hU31FDIx1jo4jIpf3u54PDezMbjpDzUpkRN9LueVC-0zx9ErDgR7qlYJ88LsUcVkmH1-SJ9dj4TCkssNnZX-MzGsC7P9ylnaCMkiES9KmACin1RYeRDIR-xVboH2rUsg13sL83oA',
     'width': 1500}],
   'place_id': 'ChIJQ2BfH89TBogRlmTRnuqSnJ8',
   'price_level': 1,
   'rating': 4.2,
   'reference': 'ChIJQ2BfH89TBogRlmTRnuqSnJ8',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 855},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '527 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.074697, 'lng': -89.3945956},
    'viewport': {'northeast': {'lat': 43.07612972989273,
      'lng': -89.39324297010728},
     'southwest': {'lat': 43.07343007010728, 'lng': -89.39594262989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': "Jimmy John's",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111332065520754768145">Brandon Burkett</a>'],
     'photo_reference': 'ATCDNfWeWjUsXM-NrCWFlbXOvWMB4ranVghFzYUpfWzzkZJWGPM0_zFIPI2gMh_fkTdmg78wOJMZB2KMaHBx_SCn7PcnJ2a_tUObHgs5qGjDsEtT3xXep4XgQlVmUHVt9vDUAA22GiwTrlJe2_obV0F9inAp5a_YfAyeBJs6JO1ZyzdBFOd_MZyqCNh_mm4Y_mddeaq33n036YxbQZ6Yo-98mTgcrWCDj6V0-EhDC9IsaSWrvZ-9qbffy7MsVj9YDkZtuLUES7qxxK5GQMRdr8fAC4pwV4oxHddsEgAQneaF6Aw7ZrIOcqS6TQA6RZyWkBZqFLt_6HHIgBrfK_EEUp0ENdtbw4JbHc_vxXmtQ9dilWAzpj1-KadjeBmeACmvZVbYaLTsWSJqfDueIddx2sCKVsByoJsiMsDSCyC-GPH9-xgGQ7lbNx7h0EdwTOwtLmR7_zSHovd4snbRmofpQ_-PP3ZMuhDe5HXRBmiDTNQ6uSasiC7Xdbq9ka2v0ORjipYdte2BvK2gj83SijtyhrntmJfspvWY9ncB-JtSiH2yPzDQj-yokBl0VBb0lMgGylW7xo3VnUvE-3h4VQ',
     'width': 3024}],
   'place_id': 'ChIJaU25wTVTBogRpwfcyNNxInk',
   'price_level': 1,
   'rating': 3.3,
   'reference': 'ChIJaU25wTVTBogRpwfcyNNxInk',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 131},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '615 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0747927, 'lng': -89.3964151},
    'viewport': {'northeast': {'lat': 43.07617642989272,
      'lng': -89.39509367010727},
     'southwest': {'lat': 43.07347677010728, 'lng': -89.39779332989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Poke Plus Madison',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114301644913664020548">Olivia Li</a>'],
     'photo_reference': 'ATCDNfWLmMz5Gk64m3qOzFezeWu9n540c6H8A3czdIssqZHGuu3Fv8R9yBIh13d5mGBbnuQmStWkQQ_Ja1Qhja7CqAv0Ku0zQr0EYLIUzZt-i8ylNayx58XqUNsQ1F0uAhPaA_fIm7PT80O-M82m91Olq9JtBfE_TEUmXPgwHv5r-tnQ8g-8BHrLI54fSDonyuQL9flamRlbhlBbyxkS22bPfanLlHMNgT-wrPxVrgAdwKeCAMXWKF3FzUK5iHC4Cc9VmRNnRharTGLeiNyq200MyzihQeN9OZGGCfZoC0N8aQKXkmyDLlho3eozHboffzP_3vWX7t6Rn-WW27H-FPnJ9Vc1Im1ynUETf8AB_sxE0UfE8MSsZ_Jfp_W2wBbQRzYj_JxQx0wZqDiD2k8ktzC2PBjvenDR-Tde6Tu3uxHaq2_yZOZoO-leK_sEaNeR2e_QBhF__DR1tnh4SVW_z02tQFpgnIQkhguxApaQiLvCdOnuxQ-kU3cN8raOkvG695MYHXRs_crVUpleGe92smR4_mr6fbV0S3G80a0Z8UG8xhJ0WbuUeWIqY2KjUEx4Wb8Kq2Y1WtJTKj3nXA',
     'width': 4032}],
   'place_id': 'ChIJNVWQ_89TBogRx4KbbdZ5jP8',
   'price_level': 2,
   'rating': 4.1,
   'reference': 'ChIJNVWQ_89TBogRx4KbbdZ5jP8',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 151},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '652 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.074998, 'lng': -89.39652099999999},
    'viewport': {'northeast': {'lat': 43.07632042989272,
      'lng': -89.39517112010729},
     'southwest': {'lat': 43.07362077010728, 'lng': -89.39787077989273}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'sweetgreen - Healthy Salads, Bowls and Plates',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103323540611018747531">Karin Miller</a>'],
     'photo_reference': 'ATCDNfVzLjiXv9MjIAuZjFQtBKmbA_5-r1oI6SOhSn1r1sKn6GccfVKHTI6d8a2ff-CmM6QsAJuJ8nqXkmQvfOh1J1vPPOI4ZQWW4oH-sYD1Rh3ObCM7atw6LOWAmxnOL7pPBfX0b7lMJ6BGwMUEXdtbownEiFPooSLA8yTFAJFzdXKr8Sdwt9Setsx_vg8Csrex5SU9h1IGv4cfVT4g66T2udgPwA3pBQqSZlwUj_QP8LZLNWJ1JJWvQQQpx2ios33HqCHY1pk6uN6PBO0PwFNGYj7y-4hkSw_v728fyjmDGBPsD6g4l-KPgXA6zHESwnfULma2q1h2zddndX5_jbfGQRJ5IVXhz5A5Db4RskGw4bv2vPlCcSLwHI57Ue051uh4j7daecDSuRRmyaWG9WFSeMv8O8AltpPtLBpoANXZjU0dEBWXwi7jcocJo25eVwRnM8OsdRrsVnsvdpMLmnQos_w69RVsklVRCWWwEfBhD2aSmrOWoLtU6R-lAeWe9UwP4QDFwW-PP399jQ6NPVI8SGyLBoWSjXv9AJAxmby7xB2f3rNnHqvr2sz2q5FqvFtfULQtBV74IypgIjDiAyZdQfmXpnU',
     'width': 3024}],
   'place_id': 'ChIJCfHMiVBTBogR0nR70wac7xM',
   'price_level': 2,
   'rating': 3.8,
   'reference': 'ChIJCfHMiVBTBogR0nR70wac7xM',
   'types': ['meal_takeaway',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 91},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '449 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.07458039999999, 'lng': -89.3934415},
    'viewport': {'northeast': {'lat': 43.07598792989273,
      'lng': -89.39200282010728},
     'southwest': {'lat': 43.07328827010728, 'lng': -89.39470247989271}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': "Jersey Mike's Subs",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4667,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106990004538469778852">Jersey Mike&#39;s Subs</a>'],
     'photo_reference': 'ATCDNfVLU0x917BlvuOJ8P8pzthM-ufDsHFE-Kio4xSvU5aPXc0ihSBeCMmz3-RLrMzh3n7bCDgf_LG12LUYGPEm1Vw9iOMGFIKEIFq_M5OPhcJ0yMW8pOZaRj1G9aZ2b_dPNLwCAmC6n1EdPVJe6b3I7M92OIMTXjEP5F_-XdfR2Jlmi6rQk6G4xCzsOBKBVFInHuCCWHcwOsisgc4_Z4YEHrDbTkYbNISfM1axqkWYkAd9f32P-EFtNG7YfVxpN2MV4PZbofDnBU5oixwM7H5EQcLBOAakj0W50hzDfHbp4iWwETb97VH1C9STEgWfvb5KGunvtNB0-kKTlK2oFd1hBkdy2rUO-yRbMbHwX92Q4KTrmD_YEoXN9bxEehK3vcq5aVYeCsR-RI93eoI_yPPTpz0Dh3f5kUG3SYkdUGG4bLzNGzd-R1OHfEWCbiGxl-WwVTIkU-EIyLtUMYsYRsPk-F9IyVcDkzeOKXQ_2zSMCoaOqfnZM4VRiFC1N5CJ_ynVi8GwlGuw85hFz210j6TmRV5uj4EOwOqV0yWevLoGtGGfFcSeViywqBKFNBWG0BGmOKqt0rJFJ8yWoQ',
     'width': 7000}],
   'place_id': 'ChIJ87b_8xtTBogRxa6RMxknUYI',
   'price_level': 1,
   'rating': 3.2,
   'reference': 'ChIJ87b_8xtTBogRxa6RMxknUYI',
   'types': ['meal_takeaway',
    'store',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 45},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '102 King St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0747636, 'lng': -89.3815616},
    'viewport': {'northeast': {'lat': 43.07618917989272,
      'lng': -89.38019147010728},
     'southwest': {'lat': 43.07348952010727, 'lng': -89.38289112989271}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/bar_pinlet',
   'name': 'Tipsy Cow',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3120,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111859829019216628948">Cody Phelps</a>'],
     'photo_reference': 'ATCDNfUVuJD2WchOdtONSFuOSHl72i-gYLJW6JSQWBawOQTwbsdUjNws2QK4lx4HiAiUvYzoE3C-BFm3WZKjiqXskEDhP5-lRxJe08EG14gedp4bMeyNwyy2kkj1FjUPwZGwX_-XrJgBdESNJNvD6WkYD_aBpDaxTQr9E1U7PZUsWHpXRED5Pd1K1dxfxX8MEU4tZXqWT6keQNXdJc-aUPz9umNTOxXi6TiQl_U4GmW_KuYeDYMumwryceZRKaWQdhMbyu3XfEqG_-b6qL17bRzpbcEX9LXctbtcOB85nt6dQhctorCf2lNzn1bcDRlRH3qsBllZSMRi1Hb1UnURYld1HXs-G3PFEcJVY2jBFgSAxMPvdtrvRRdrvsDd0ezq-lQhNsKPw8Xco4omGgZrjpKH9j2InKu89OUaivzh4uesqmKv0HZ3Avg4UrUM0rYAXHmkQ-vdVdUQLjhCNvq5nH6yL-Qkm4uS_TtPfsU3IrO411T6Evw1JdGaGvvfojhMrMWYHFFaQvZs-pFtgcKFLugLjF-c3V6TwmczEib5wIj3k3kK0W5PqaamK0JVN1QvBkDERYZmPs0p',
     'width': 4160}],
   'place_id': 'ChIJBU15oT9TBogRab0MYkIB2I4',
   'price_level': 2,
   'rating': 4.5,
   'reference': 'ChIJBU15oT9TBogRab0MYkIB2I4',
   'types': ['restaurant',
    'food',
    'bar',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2136},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '505 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0746077, 'lng': -89.3939783},
    'viewport': {'northeast': {'lat': 43.07600762989272,
      'lng': -89.39255822010729},
     'southwest': {'lat': 43.07330797010728, 'lng': -89.39525787989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Chen’s Dumpling House',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109206063382211265455">E. ARTI Wulandari</a>'],
     'photo_reference': 'ATCDNfU4mGdtmrExguiNGdbdSHQRAwIEOxmvM6vZemL-sk8GUBZI5n-dnattLEbL5loq3tFPB0xNY9Xk1UXZTJI0g3UNI4ZYl7N-J30kWR7vu4wcMQKaIE7HGcVQYv4auFJ6n5l8p3hSQU8l4mpBSL7A-KtmiSN_bcwjeacFmcCmkmui0iNYPUHT0f9NJPHAVdEY1i1Q6csaOJ3bTImfjCOxREh9BJ4r23oEfgO5OYFWO8-MjmyX2UOEswsjzvzFGXri-r2sm8geN9Oj1ii_9hbGSEeONtQHSYaf5t114oJgs5P-Uq-z9TGKQ-otJ8ofb6oiTeHw0DAfE3lX8n67QasC1w3n0K3GJc9v74TpbfFe-eq6gHGnhrhvIT1TgGoRCtj-3RqqXugySRKXviCTaalC3gl3IlmhJ3liSAX7s-RP7vKTpgmbg4aEud20vrqkgTKO-q6KNiyyHg9iekk6vSCuQLUWI-Dfe-2DKOXBuAY9ydKV4rDLGcsZfUpvQ2cf7zt51La5f8jy6dADJgSdTRyTOiMvuWQzoC7-EexxkCB4IYGZ8fsAwUX3ZfbsFu1l6zm5fbBfTLCZsY-eKQ',
     'width': 3024}],
   'place_id': 'ChIJeevQ3jVTBogRektxgc6uLXM',
   'price_level': 1,
   'rating': 4.3,
   'reference': 'ChIJeevQ3jVTBogRektxgc6uLXM',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 584},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '449 State St 2nd floor, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0746449, 'lng': -89.39346019999999},
    'viewport': {'northeast': {'lat': 43.07603862989271,
      'lng': -89.39217917010727},
     'southwest': {'lat': 43.07333897010727, 'lng': -89.39487882989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Yume Sushi',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2304,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117418598659693915697">Yoichi Murase</a>'],
     'photo_reference': 'ATCDNfUAUoM1DU9yUL8rQxz-EiIGoKL5vg6XNMiUlLnb0Xi4XbrDNAqQckpGHvzZwJc7t1-rQTHAw6dq0LfY06FsIBGPiHl-dWsDc0HIIoOUY_MSAOcUl0D3dfulg3z6kw37qmWSiacf2yIC380xfl1yC3W0Ip-ZiJkVyH4hx23SWYeoW5xzL-iAt0LNFnEvYrHedTPUzGkOMBFzswRWU-udd7_z5x_keurMDclzWwSEM1qlIUer7n6UgsTzkuVNRV8Fc8qSnjPQ-YZksGoLYVq8rrAZY8ltfU9HME3sQG1kbJTJQcTXrHAHxLhoWiOJIhkB_DlduCBUUnsbHsiuN1AoRKqVDc3o9J3LWYnOFdGOTar35mnvrAXtveXAAvp7nFpN0aC9ZwsHDGd95wrUoqdp2kWP8BjQhdg1PiszKSQ2-HXx5ZmeN1ke5hcekZHDijZHIme9_H3soYYw6tZgHPG9w_ZrII1zH6qsYmXilJBIAItpjFXsDaxRy6jlrV6_j9Rr1LL5F9laoggg33ntE685wRDEHK1blHjc6Q0fdd358SWh1xNxsez3oJKDBbFlFaIHib-K0xkp',
     'width': 3456}],
   'place_id': 'ChIJJ-zlczZTBogRM3JXw0WwV3I',
   'price_level': 2,
   'rating': 4,
   'reference': 'ChIJJ-zlczZTBogRM3JXw0WwV3I',
   'types': ['restaurant',
    'food',
    'bar',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 249},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '414 W Gilman St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.074533, 'lng': -89.3940635},
    'viewport': {'northeast': {'lat': 43.07588507989272,
      'lng': -89.39264137010728},
     'southwest': {'lat': 43.07318542010728, 'lng': -89.39534102989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': "Paul's Pel'meni",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107466052423958092626">Howard Chen</a>'],
     'photo_reference': 'ATCDNfVvq-67SnKJ39OuO7Vra_FHOc8BDYHoUiGCE3nSN_PCLixlYwNGi4vctYOAZoIIy5Yai_nMrg2vxqq84ttPxjqFeyKSRP4-ozqbR4S9Ycg7hlaUfS5rzNhPAkbDtwakWi-ihqwZpHcCzplRPtPINjsiGN54C_kL2OgQmY6y8yCx4vEiV9lbsdp8kdYzL9PyXzoUbQs9nfxrEUtftcCpUg51SD_B519dKuCLrSEvBRkdlQ5vAzMjRmJyVDZN4EWhB3BmzUfk9xBci5OmlCrJyXpCxhn3n75SlfkWxijU5Br__2y2l8ogJpBVKQQw8stdV0IdaBIHEGafomgfimWzpgPEW-5DfY_m1dpf9CgfxEXgIOddrktw1TF8K4iLTGY8SWtwtQqssfW3FWWzpNnDHhCkbS0Ke4Q_vDJW5yTzvA81fFv9WFL5A_K_3nhM_Y8Rebyc5cl3xx5CcfNNaEd14oZ2sU0fsqEgOoJBqlDBqWxM9o6iM7P3VHb02Y8_u2TB4LAo_cZayOMTXRxsj6o6aEH_IlaN0nm_98u7ZldeypSOLRbzAqZbptjCTormkHgWmnaGQpsf',
     'width': 4032}],
   'place_id': 'ChIJ-SVAyTdTBogR2-15dUFGTew',
   'price_level': 1,
   'rating': 4.7,
   'reference': 'ChIJ-SVAyTdTBogR2-15dUFGTew',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1750},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '317 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0746826, 'lng': -89.3908656},
    'viewport': {'northeast': {'lat': 43.07608357989272,
      'lng': -89.38951352010727},
     'southwest': {'lat': 43.07338392010728, 'lng': -89.39221317989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/bar_pinlet',

In [30]:
maps_client.places("restaurants in downtown madison, wisconsin", type = ['restaurant'])

{'html_attributions': [],
 'next_page_token': 'ATCDNfVbGeqsM5TuzKmaYSQhrE6jl65db9pDRjQlOKdVB7baQSqL4EtDcrlP3pU8jRn4rXlc_7o4XSP6W33RCqr9i8xVz9t23Rrx4Wo3m8vWjsLUNrB6uWWBjvVzbEAexQVyiKJ8a-T6S6x1LrCEoulmzmpHVchpdzRrY7L9AytyMltY-Oe6mDld9BxJT8eur_fNXDiLA2d-ZC75wriixza17_X1cdn5ukm-OM3tITASXILiZ2yz7I8uHVelxC20JxHhiDwQHiF7k5PuYLMeUoBDPW5hb2uT6euX6S9Rj43sAg5ClnqZ_Lv7uPgLX3fgudml13QvrljxYHSiA_MDpidfLmoZr1hlN2YxQAT1qea4d3V3s_5wytjj09xT_gGJXYovUtcZigQkry1Vk8c7B4PxWOY2kZVIQNp-ziUGVtU1pog8PPI43EyJBRHuDFMaSTk5uw',
 'results': [{'business_status': 'OPERATIONAL',
   'formatted_address': '206 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0748792, 'lng': -89.3883548},
    'viewport': {'northeast': {'lat': 43.07620632989273,
      'lng': -89.38701412010727},
     'southwest': {'lat': 43.07350667010729, 'lng': -89.38971377989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'The Botanist Social',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107497128421467390457">Elise Hallock</a>'],
     'photo_reference': 'ATCDNfWCBiZLUjncQf3rHetC2NQ-k59bj9PK10XHT4JNeWpVAZDedeI291W6Ik2d-ce3IHy4fsY7NijURte0HWoJiYzV3COb5YJwOVysc5OUx-dcV9rB0fIkCSyZ5MUw3WB_0UYhSXNCrLVtOh2joBVK8DSqeXko0EyeOGSGvl1umQhabMXi0iXWwp1wLNywcQuNw3vMQfX_BlEj636aN--R1TpTDSEtrTY8sxyBXsdhGJebNYRNY27_ZZuPSiTg5hRdvs23Na9ZHjMz2E2hDKRL83zryL3RCNxU0tFimQHr_f37PHTVdIqRSTWssB1AP_9UkI-NmDQUQOwq1L-Gm26ITn2zXXknhDk9_UqjASLiVKWTDC2jSW6VkKOWRNXyEe8o5dwUZHjrYUSTY6NRILpj7PYcYypcljN7gUKuJXp0FVLFF3jsrG2QpHTkYyTxO4DN62UcyXU5iilg5a6YJp3A7NXtI-Gkn_hufzv14iO1gZrl3AvYTjZP4LAkrVE-TViqswPXgtd-o3a0OjVQKcp0on3iTBGZcQX5vaOKPYwTXUSYLcgYqBZr4aoxWcqOpEsKfQ9E_ulN',
     'width': 3024}],
   'place_id': 'ChIJgctqeEZTBogRzXAwmYqT1mk',
   'rating': 4.4,
   'reference': 'ChIJgctqeEZTBogRzXAwmYqT1mk',
   'types': ['restaurant',
    'bar',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 528},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '121 S Pinckney St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0742365, 'lng': -89.38101189999999},
    'viewport': {'northeast': {'lat': 43.07553082989273,
      'lng': -89.37977902010728},
     'southwest': {'lat': 43.07283117010729, 'lng': -89.38247867989273}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Merchant Madison',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2848,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110199422075368032873">Merchant Madison</a>'],
     'photo_reference': 'ATCDNfW10OJOV33iYBPvFmDQ7UsLP-GnjoRFBAqAFbx0ilDns3b50FQfCGeiDQHqHIRJvoUhvgH4JAzr_lYZ7M4WriluF7OChOexAhWNc8WCxSYUiFwkvd5OyIKRwrXN7lh1NH3ptda9hCiEqV4Pm_3kc5RALzpM66Hx4anRh4kyP1mnxIe0cNuAEI7odeS9w_bR1YFsn9ji_MQ6WpPSr4oZrnrDucfCwoLbC_ebIkY12OjJq7fspv3clk1n88KnCoqtH6dKjQflJECgzfpjYsFNyzxNshbhbxm9qjw0LwdT3K12ZrPiIfwq1lfu1H9ouyGUG_q_F-PIKFRkNMqVDCEP5itSb9fgDbO0Gh1U6o-TTIoYQu0ngG9R_2J9s4ndosyO73sTZL1ImgD6u0z9kLwFBEWs6t7QdWVT-RhlqMhQZHsGm74gGTwbHx62sNZmBn6nl-sK_dTTKi88Hw7_hBee2j-XKAHPUA-98HEpmQNvu2sJmaea7Uo7G8VSDPOKH6ET5XR614dQFvFDjoRHUH-YjoVy6SehTpuuUzBV09t5tJQ39QAMk4oJAYQ3JzyVzpy7wAChZM0BG9lshQ',
     'width': 4288}],
   'place_id': 'ChIJ31Hrtz9TBogRrTZd9f5DmJo',
   'price_level': 2,
   'rating': 4.4,
   'reference': 'ChIJ31Hrtz9TBogRrTZd9f5DmJo',
   'types': ['bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1397},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '1 S Pinckney St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0751379, 'lng': -89.3822319},
    'viewport': {'northeast': {'lat': 43.07641967989272,
      'lng': -89.38099887010728},
     'southwest': {'lat': 43.07372002010727, 'lng': -89.38369852989271}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Graze Restaurant',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117758139139155162468">Paul Hyeunkyu Kim</a>'],
     'photo_reference': 'ATCDNfWL6pT16wYNErpdt-uE3ZY8rwzq3tm_zGQUsMDecqwKL_sphU_WvJAD2MP1bXqCIaOuNG43A30wsH42EIHg0iy_nP1hC6mDcszKRjYbJ4gTKDgUf-A_ZMZJjL2Qq2SE2Uibp-Ouz7q2kZJ0v9h3RntswuS_ReR18TM45eFK4ZY7JtOjg_DJMDd_spSmdmlEupDUgou6G8cifU0udHafTt-mYuNX9kwO9OnkXywou1Yu8BQLFbjo4ITz6ahJUNa8pV42aQuzQrA7_vLorUHp4cvZYX50q8OHO1I_ZMYtjQzW5FCLF4nMFIJKW-P2Hxl-SVJvN9MaXoYLadHty5qC70QXaY7toLKtfH92hj4ehFfRXMwWfXQBM-O4iqffMCDrUqM8VizRdwIPSYuTNbiheLJFfEHpLWXpGvIg4AQNABrsGG8nrzTM-ktryWeTmQA-FDCEDbDrXtmXVE-yspQgL9VI-Duz0N_NP_EoJm6mD2QBYq16IPI_C-jpVd_nlxpbazLu0ca1deVKyYnzWR3HueIrml6UdbfqKDY63NFMhOcG46CXuMYrRRGB46txtWN1dGtndZGdNBwUfQ',
     'width': 4032}],
   'place_id': 'ChIJy_R_dz9TBogRz4rN3JmZd4o',
   'price_level': 2,
   'rating': 4.4,
   'reference': 'ChIJy_R_dz9TBogRz4rN3JmZd4o',
   'types': ['bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2028},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '644 W Washington Ave, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.068292, 'lng': -89.3949751},
    'viewport': {'northeast': {'lat': 43.06966552989272,
      'lng': -89.39361297010727},
     'southwest': {'lat': 43.06696587010728, 'lng': -89.39631262989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'The Harvey House',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 1651,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117585224965649453632">Jack Probst</a>'],
     'photo_reference': 'ATCDNfVgSMaiS2bmsYWAPib8G0BZ-g3Qt22mTJqeDBxFqgHeGZeDG5oponLSlbuNJeLEAuyPM1wUsSRb67BQMS3CUOS715r4ST-BqMPxg4ZWlSiujkHPPFoqZqpIY4BddCxjzZka0wnL0D6lbVwrYa7yXZIqqH6NP-XKce3f-RIpS21WDB_VVUWLNNZUPdOjV2A2I7X1E7z900ty3kgCHmIaWFzxIyeoc406zsUA22-XdZwkJLxuL7d27CHSd1_457XC70zo1MgtYpkBhcHsoo04aqPBzzQ0kpFmB56DfScb6h-V82vumqNhWektgTAofsMNeeK8AU7Q_4yBOUR-rPna4V4KpZGITYmJTs4W1Rkmbw9vce4pdm8SJj8mhFzCMQSsUAsygwYvtmPwAoQnHhUR3fWmWr2zavN76ZUU9f8vDM3mZmja981czkWVKwWN8SVRt92hDRVVviF9Ncb5wXtpy__ygcXrEyXp-dYdgmOqcCG2XSnq2be9v4cxf5XGhzTm4m33nZaIHNS7Ksuw6NUfUPcbQqlYyalskH6jwFmNFP15umSZUjMA-awVKH3Q4iHbHw1r_zg_',
     'width': 2202}],
   'place_id': 'ChIJX9En6gZTBogREjWBvkYxbiM',
   'rating': 4.7,
   'reference': 'ChIJX9En6gZTBogREjWBvkYxbiM',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 899},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '117 S Pinckney St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.07421799999999, 'lng': -89.381152},
    'viewport': {'northeast': {'lat': 43.07554217989271,
      'lng': -89.37987107010727},
     'southwest': {'lat': 43.07284252010727, 'lng': -89.38257072989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Settle Down Tavern',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2770,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105901682085285908863">Settle Down Tavern</a>'],
     'photo_reference': 'ATCDNfVw7qyxcRa6RvRwQdU7o9v3QT2onKHjjmgG6a0OVTXV8lLN8uj6OZP49rS17T2151S-EfKlEmp3qDxRqfQSPE4G-j5Cmgt7IM89XD4wOvdiGuHoBDFy_xAnutrrbS3KCoqVWjDhw5nDEh788cNJvKyew4wD7ow5w9DubeSDePAjN6VODBn4gGPFuny_ZiHsKEwNoMXmm7czV2Y5rmt7TR9r4GQ3glMAoHo_7INaYzzpCfTLXgQi3lAGKVDbJfAdY2ytG-HO-zJ7SZz3AzySpwNIMhRmtv4t4v6cOGPRlzzYlQhFLXE',
     'width': 3463}],
   'place_id': 'ChIJEyqksthTBogRkik5oMCE1Yo',
   'price_level': 2,
   'rating': 4.5,
   'reference': 'ChIJEyqksthTBogRkik5oMCE1Yo',
   'types': ['bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 556},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '351 State St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0746997, 'lng': -89.3915933},
    'viewport': {'northeast': {'lat': 43.07608732989272,
      'lng': -89.39023747010728},
     'southwest': {'lat': 43.07338767010727, 'lng': -89.39293712989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'The Stuffed Olive - Madison',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2268,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108718831106319834519">Jim Hopton</a>'],
     'photo_reference': 'ATCDNfVKfZevpMobZj7iyuHPXNpt4V8CywOmp2iju24q1jBEumPslEL7gQ7ymRV79FP1ZBS6myZcZRzOVzLmHQ6QTzPatf0Y6_FRsI8nU26ntXAwSuqdPsCvvpYh0cb87oTSyKf0nlScK8SB8VY5DT2Pte2CnRLWyWHaUmuGwZtKAZmgmwMZ_025KFOnY0wugcRdlPhzUDmHglQ0gyPk392XRJgei5sJ5hrjOZdyd5xNrRChcPSR9XOxudWhFvAm_wbcNJpdlfGiLS2xOLWWG7g_TCKkxFKnfndXs1buBAnPMbOBeBRO9Bx3d_Z2XQ8wFwTjNGdAP35XzVlBJ9MNOn4tWi6qHrDZkwgAa3aY2PSQdXMjbBUNzmC-oIDuIDINgDUwtpio7mPJhHzdXBzHa18hbOzJSX9kQyjLVMkf3nhtjEmf_lILFR5h-NCwDl48WXhrWny8dOyYaqF0JgWVSWQk4iBmh1TGmTJgVtlCDbq1LvMspMnChRySeKCT-uCBJRd1tI6QBtY0d7xKJlnKy-8IBHLm-DPIzX7FT9Eq04jgw4hptK4GBiDP-ZgaTjPTwZsP4VjZYMdcgTk9mNxZM4dHOGlNev_HEw',
     'width': 4032}],
   'place_id': 'ChIJF1eSTehTBogREHSPhHN1VIo',
   'price_level': 2,
   'rating': 4.5,
   'reference': 'ChIJF1eSTehTBogREHSPhHN1VIo',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 477},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '23 N Pinckney St #1, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0762535, 'lng': -89.38370069999999},
    'viewport': {'northeast': {'lat': 43.07754772989272,
      'lng': -89.38247792010728},
     'southwest': {'lat': 43.07484807010728, 'lng': -89.38517757989273}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'The Old Fashioned',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2988,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108067406833517518388">Tom Guerra</a>'],
     'photo_reference': 'ATCDNfVx_GCACiwSRBI8vbnjaRA7AYJApSq5wn73OEItAArt0I6ZvPKhhmTTbMbHlyIV0aDGoSAeJA5DVVj2Su-rQWB6ofeGhuAvNrUTCBVJMs2JBWecNXPPQbq6vakgK2gR86F3cTy4VACm-NcKhBUL0PUYz_rQRrZoUeLmtZgG30G8GkL-m8gpcBc5j_7BWF5Y23hb0c_eQHGQC1Z_iKHvhWODQMM9EQ5-7iL8BhTpI6zoObgAbwiTc6ryyOYeKfYN_zH-s67MimP3aQDUOYkeWDz0GTuwvYUcSXhsyvwEDRoHWu_EsQnomnu8XzWW3HDiqMadLB_ytfNpHBIrrWWGTnuLGiZjKYbM9y0YtVjsxV1W2phivCAc0V4c4XKyk_OebXrQztX4zjgz8u-zHBfrjIbrXrV8J1yLwUofq0wYj4_QSB98hSzBq-ch3h1yYn4voBHB1eQlw3NytwH2_S2b-LgwoLh8eVen7Mm8r1EfLOiAFCZzcvPoevnW8GzwPMRJQvcJYSQ1DKeec425Vh-vemExbSdP7f3m7KLdNBOSO4lB4p_Gaqg3DO7DKGjXngIhTbmGg_JmouUFjw',
     'width': 3984}],
   'place_id': 'ChIJHxgqqEBTBogRJLOAk9gWpBg',
   'price_level': 2,
   'rating': 4.5,
   'reference': 'ChIJHxgqqEBTBogRJLOAk9gWpBg',
   'types': ['restaurant',
    'bar',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 4773},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '123 E Wilson St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0738186, 'lng': -89.379002},
    'viewport': {'northeast': {'lat': 43.07526247989271,
      'lng': -89.37778047010728},
     'southwest': {'lat': 43.07256282010727, 'lng': -89.38048012989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'One Social Food Hall',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4284,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112257688727614078511">Carl Rue</a>'],
     'photo_reference': 'ATCDNfXudiMm2T0jbPavcAuVaTvZAjAUTfHHNdqlxdGTw0qHBwoxG7uDtjNzi_nRZQArGlpUgZouW9ohnD0__KmQYFKs4m7YAOS7KOzTBxF3bO_NNZw819OMeYR5Oq-j11SrzG0fQ5I1zrF4XP2bkDsD58l_Z9TkFLlxSCqPTixL-2Lo-WrTEPs6GEVdylOze3biakfn1rgfYQQtoaM-1nqY2T8KLa0byBsAvJt5uG4veGJZK6fOlMtCMYZ0DEiXsRcW8Pm5q757rMqSaYj1fkHlMUijrcV7ZIR1Q-BcSpPYsUygZ9cM2tySnfGImBK6Ae1vOabQlff-zLtGg2GqCsPPLw_V1v5yhOXilxmLNnW8rpXqKXVYj1UF6tZdLXMZn3EkGMPGhG_IXiOptXLeTb25-T-r5MCK078Io_LXFPgR98cZS9IfVvuIJXhst5EQZAqRXzfvdpKWwq9UDLLqA9ZclbsqQ08Fw7VKnK6oxKwJ1KHBZ9dTcladNJ0MmOZsYNMkEWNbpPSH8DfCOQvKMBZHCcQ6INR8P5pG9HZYqJiup6jrVKeemxP7oN8xdBvsV6WMNjGG7hNYbmDqZ9LA1KjRNqRFnGFYtA',
     'width': 5712}],
   'place_id': 'ChIJIao3xuRTBogRFDWl7GjHt88',
   'rating': 4.2,
   'reference': 'ChIJIao3xuRTBogRFDWl7GjHt88',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 55},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '119 King St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0745476, 'lng': -89.38068369999999},
    'viewport': {'northeast': {'lat': 43.07591152989273,
      'lng': -89.37933027010727},
     'southwest': {'lat': 43.07321187010728, 'lng': -89.38202992989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': "Madison's",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116462393656220000926">The New Radar</a>'],
     'photo_reference': 'ATCDNfWbpmsXlMBZ6Z_8SWfXjg5Z32RNXliNR1tfcVvkcgwRw3gLc6kwFHBivavz9tMswq89aHGG08f1C81TFbttO6F-z94p05rj546xXN1dTff1ivFGqmGj5eNuVpp5qkUqE3J4G7pqGtSfBymY_b9AzshejwGkj231ypPWWcOjC0HsXYOUsJ83SRCJ0d0P61NE7IjdXLzkL8nBQpRrxuynVjv4qJR7oPByYdxAwG081YLI6ub0iHV2yzrJxMh6NyVptx_e9lass9sRZ1NNGg_B9i__xRJ8BSsC7yQ0ZZ6ACdzEa4NM1b_GN_2bm4LFIwkc2mqxmWbGZ-qyy1chcObqVh9R7HeM0NsUvNFp8mCqRxj-pJj9sgp_APEtUfznrSHuu9Jhz3G4xRwsWQIHDWSdCBnR1BH4L1xVP9XjLR4ZAOm_bf0p0EsFLAqGZdMKqjapppIyFQ8v0IOsZISQ99QbIMLVf7XkBCBZM3eeQOqdggGokL2KbOx1eCHUTJpT8-vjqqOsup3kKc44dRSmES7PT2vWpiz70R4fMrZHsYuEKHY0C2bJQUM3ziByhs1AD3ldLo0bRwNE',
     'width': 4032}],
   'place_id': 'ChIJPyrWxj9TBogRF2JT9oRyZ3Y',
   'price_level': 2,
   'rating': 4.3,
   'reference': 'ChIJPyrWxj9TBogRF2JT9oRyZ3Y',
   'types': ['bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 767},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '430 W Gilman St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.074342, 'lng': -89.3945631},
    'viewport': {'northeast': {'lat': 43.07561787989273,
      'lng': -89.39311887010727},
     'southwest': {'lat': 43.07291822010728, 'lng': -89.39581852989271}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Haven',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106558420124318345689">thisis hybrid</a>'],
     'photo_reference': 'ATCDNfWBln5LwyIaC_vUrQQDHG3z8MwtlR1q4lyTXSXMoMrOmcD1UFGcgZUnNlsctSQk13qFnEa-ccNZc85c8t1klG0TDciyE5Z8tG4B8I-jkpF2FoTxGicbJl3CtiX-zTBliOtW29ZWkVViElHImw1kTlWnw79G4gkl_tmcKjXhv0vetacD6zik8BBGDrnLB3nl2vEFZ0UrB08YUQ4cZZraJTeCpVZ60BywOT2FmA2Ztt7c86i2J4E1ct_J8VofN44uGyu8TBWUJrdEYmyEBiu9mYktbG3zJswHYa3-eHM7dUl7u89nJrTnVgZkBfvyIan5hY1Wfg8Y0_DVWz12hew26y0Oejp81DEBedAFVeoH7NZCSR_Qc8cAywhNMp5PC7RGaFomZb_SMWwKETMkgMzAER5IbTe68L-fLPMJ1ynh2KnCcYawZxLQzWJ2nTAShoNhILk7wcXPbtH0QJVEN4KJCODw4prgVn63aJ0VwaJpDJiJelWhyc3ON5Y5FvQ67WHyRSgCR-5sGJMBSKLVymJZpZ4PjHTCDIz-AC2-XzIdpkyRNYB0dT9KyizW3zMN-rdSkFNnPdJWeFe8azsQe_6Knn6AAreuTg',
     'width': 3000}],
   'place_id': 'ChIJsd02CwBTBogRj9wXntfQOcM',
   'rating': 4.9,
   'reference': 'ChIJsd02CwBTBogRj9wXntfQOcM',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 217},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '525 W Johnson St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0715501, 'lng': -89.3942742},
    'viewport': {'northeast': {'lat': 43.07280882989271,
      'lng': -89.39301322010728},
     'southwest': {'lat': 43.07010917010727, 'lng': -89.39571287989273}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Bistro 525',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2457,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104170520952266058064">Bistro 525</a>'],
     'photo_reference': 'ATCDNfX7PL1O1Z8xt1yx3q1KZ0sw5P-3EmbzUsdYtXTG0QO5ngvVfqtXAhg6VdHd2BDRJOjWLvJyfHTEfg8FVvF5OEatKDS8LDN1BJaRwLhA3flfeE0OGJpoL1efordn1AeAQLF_Wk7sYjGSNBrTQ7aFhzyi5IrczJpSrmdIbgFPUGvmnKyvnwh3aZNP83Muz5xXUvpQuEtcd6PvSGyX5QC2NNQNj55N9MA0oweYqj95WzypHAfeOy0pKDurgirlKmzHxo7z2vKIBPJUiL3t0z3CYUaUGvCa5SpfcWuKqkUVVmGmWMzdHtU',
     'width': 3545}],
   'place_id': 'ChIJ-WTrgRtTBogR9B07WchISNk',
   'price_level': 2,
   'rating': 4.5,
   'reference': 'ChIJ-WTrgRtTBogR9B07WchISNk',
   'types': ['restaurant',
    'cafe',
    'bar',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 74},
  {'business_status': 'OPERATIONAL',
   'formatted_address': '101 King St, Madison, WI 53703, United States',
   'geometry': {'location': {'lat': 43.0744237, 'lng': -89.38136589999999},
    'viewport': {'northeast': {'lat': 43.07589047989272,
      'lng': -89.38013747010727},
     'southwest': {'lat': 43.07319082010728, 'lng': -89.38283712989272}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Lucille',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2268,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115922422622125013878">Liana Rodier</a>'],
     'photo_reference': 'ATCDNfXz5RjsUmafOYoaWBgWSuMGFDKbMFvfK1vGE3b8ThiZhu8mFlsxGWmMaaucgVX_gamT9VX99bMeiPAtdnFNFTiyKOo2NsZ9WqE-h2vbZLPxdAg061tm7Uhnaes8ZMrUgqNDnBuFvKrSnlPZS_T-BhBXxETO7V2W6viWfIWAGDBOph6wOE3-JWRMn7PCpfLdUeSHrVE1Ul7BpHUJAF1QG2Hu1PK4VdkXHRVBfG8pIBPNtZjWDYleX7fCh4lXACiQC6Zxz97EznbqFNJ6DSe7UlJ6AWOB8qLxgQODAZc6BfzBYs8Ttm7LGc6ax24GlHyz7Vk32xKKqu9Z6tLU0rHugDZUr5xVBmu1Rd3U8bdGH1K4YXtreAHLyQr_jy0mD38uutjY_-lK9U16tNzPGH8nRNhmaNy7ri_lQmVMGmOEpBhBJgeKBNlKEJLWbeHwNyls8Rm384twvc_cl3hfztC4MVMQ13EUr7GBo1jg0sau3ndIc7n68X7pLSpZTH7sbITLVlUffJZGSPEqrvVJCnsLtE4mdVKbd2DUgJ7eOY32vUbNFR0pn0OEa6jkHCem2vWsQhYXYw',

In [5]:
maps_client.place('ChIJs-aLQc6sB4gRFe2Zx4HReSM', fields = ['reviews'])

{'html_attributions': [],
 'result': {'reviews': [{'author_name': 'Emmanuel Fernandez',
    'author_url': 'https://www.google.com/maps/contrib/115778137543745412555/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjX6IlZB7oQ3jQkNTyqQOSURtp99NVSq9gjMO6-qRDNWl4C_q7c=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': '3 months ago',
    'text': '(Drive-thru – 13 Nov 2025, ~5:30 AM)\nThe window attendant this morning was confrontational and extremely unprofessional. He said his name was Brandon, though I’m not sure that’s accurate. He’s a short Hispanic male who wears a blue button-up shirt and is usually stationed at the front counter or pick-up window.\n\nI normally give service workers the benefit of the doubt—they’re often overworked and underpaid—but this individual has been consistently rude in past visits and has also gotten my orders wrong before due to what seems like a lack of care.\n\nToday I ordered two sausage, egg, and cheese McGriddles. I was given two McGriddles without cheese. Simple mistakes happen, and I wasn’t upset about that. The problem was how he handled it. When I asked if the order could be corrected, he became aggressive, confrontational and insisted it was my fault. He even claimed he had repeated the order back to me when I ordered—something he absolutely did not do. I come to this location often, and when this employee is on drive-thru, the only thing he ever says is “what else” in a dismissive tone, often forgetting items and acting annoyed.\n\nThis employee needs proper customer-service training.',
    'time': 1763039532,
    'translated': False},
   {'author_name': 'Jaelinn Caroon',
    'author_url': 'https://www.google.com/maps/contrib/102290666342673075248/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjUJNTctfQu-eek3XuiaGzSq2wv9FOXWlT6AqG8e9YV7y6fI5o_D=s128-c0x00000000-cc-rp-mo-ba3',
    'rating': 2,
    'relative_time_description': '3 months ago',
    'text': "I get it. I've worked in fast food before. There's short staffing, poor pay and work conditions. And I don't completely understand McDonald's priority order system. But I order ONE item on the kiosk... About 15 minutes go by... NOTHING. Some older gentleman goes up to the front, gets a significant amount of food, and gets it all before mine. It wasn't even that busy, for a McDonald's at this location, plus there was a manager (I think) there, so you'd think it'd go faster. Food was alright, and the smaller older woman who was mopping the floors is amazing too. You get bonus points for her.",
    'time': 1762135032,
    'translated': False},
   {'author_name': 'Morgan Buchanan',
    'author_url': 'https://www.google.com/maps/contrib/100368394160100573127/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocIfi4JMlXVXzWS1NkysZzYpdRm2FuBDCzSDHDXYaEfbWsaOtA=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': 'a week ago',
    'text': 'When I pulled up to the drive thru, I was asked immediately what I wanted four times in a span of less than ninety seconds. It was rude, I asked to look at the menu, and they asked again. Impatient and unreasonable service, uncalled for rudeness when they extraneously added a side of mayo to the menu board. I’ve worked drive thru. The impatience drove me away from this business and it was so unnecessary.',
    'time': 1770499173,
    'translated': False},
   {'author_name': 'Jessica Tec Cob',
    'author_url': 'https://www.google.com/maps/contrib/105086313805536168060/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjVkCXF5mOHlFoEWbj3nbxMo8Ngs3g6egq6u8NY7manm7sfSOZRo=s128-c0x00000000-cc-rp-mo-ba2',
    'rating': 3,
    'relative_time_description': '2 months ago',
    'text': 'The sign says "try the grinch meal" and they don\'t have the grinch meal. The McDonald\'s on Park St has never failed me like this. I went to the McDonald\'s on Park st after this shit. They were nice enough to refund my money when I cancelled my order so you can have two extra stars.',
    'time': 1765528164,
    'translated': False},
   {'author_name': 'Eshan Ahmed',
    'author_url': 'https://www.google.com/maps/contrib/109871303240301440769/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjX5LydGVkSQkiLz0kNz1n7GLFJ9quNdAGJDdUgWwL0vXdtabelF=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': '3 months ago',
    'text': 'worst fast food place I’ve ever been to by far. food takes too lobg to get prepared, unsanitary dining area, most of the kiosks dont work, the food doesn’t taste the best… the list goes on. every time I have gone, there has been problems. for some reason the people at the register either speak only Spanish or call out the wrong number. they also always forget to give you the sauce and the drinks that you pay for.',
    'time': 1763699017,
    'translated': False}]},
 'status': 'OK'}

In [197]:
place_types = ['restaurant', 'bar', 'cafe', 'fastfood']
restaurant_list = []
bar_list = []
cafe_list = []
type_lists = [restaurant_list, bar_list, cafe_list]

results = []

area = ['downtown madison, wisconsin', 'westside madison, wisconsin', 'eastside madison, wisconsin']

place_ids = set()

for k in range(len(area)):
    for j in range(len(place_types)):
        for i in range(0, 2):
            if i == 0:
                response = maps_client.places(f"{place_types[j]} in {area[k]}", type = [place_types[j]])

            else:
                response = maps_client.places(f"{place_types[j]} in {area[k]}", type = [place_types[j]], page_token = next_page_token)
            
            
            for place in response['results']:
                if place['place_id'] in place_ids:
                    for establishment in results:
                        if place['place_id'] == establishment['place_id']:
                            establishment['our_type'].append(place_types[j])
                            establishment['our_area'].append(area[k])
                            break
                    
                        else:   
                            continue
                else:
                    place_ids.add(place['place_id'])
                    place['our_type'] = [place_types[j]]
                    place['our_area'] = [area[k]]
                    results.append(place)
                    
            try:
                next_page_token = response['next_page_token']
            except KeyError:
                continue
            # We look for a next page token even when we aren't going to the next page
            time.sleep(2)

In [198]:
places = []

for place in results:
    try:
        curr_dict = {
            'name': place['name'],
            'place_id': place['place_id'],
            'types': place['types'],
            'our_type': place['our_type'],
            'our_area' : place['our_area'],
            'lat': place['geometry']['location']['lat'],
            'long': place['geometry']['location']['lng'],
            # 'geometry': gpd.points_from_xy([place['geometry']['location']['lat']], [place['geometry']['location']['lng']]),
            'avg_rating': place['rating']
        }

        call = maps_client.place(curr_dict['place_id'], fields = ['reviews', 'url'])
        curr_dict['reviews'] = call['result']['reviews']
        curr_dict['url'] = call['result']['url']
        # curr_dict['reviews'] = pd.DataFrame.from_dict(curr_dict['reviews'])

        places.append(curr_dict)

        time.sleep(2)

    except KeyError:
        continue

In [199]:
df = gpd.GeoDataFrame.from_dict(places)
df

,name,place_id,types,our_type,our_area,lat,long,avg_rating,reviews,url
0,The Botanist Social,ChIJgctqeEZTBogRzXAwmYqT1mk,"[restaurant, bar, food, point_of_interest, est...","[restaurant, bar, restaurant, bar, restaurant,...","[downtown madison, wisconsin, downtown madison...",43.074879,-89.388355,4.4,"[{'author_name': 'Pam Buss', 'author_url': 'ht...",https://maps.google.com/?cid=7626445242483372237
1,The Stuffed Olive - Madison,ChIJF1eSTehTBogREHSPhHN1VIo,"[restaurant, food, point_of_interest, establis...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.074700,-89.391593,4.5,"[{'author_name': 'Denyse Nizam', 'author_url':...",https://maps.google.com/?cid=9967721014283432976
2,Merchant Madison,ChIJ31Hrtz9TBogRrTZd9f5DmJo,"[bar, restaurant, food, point_of_interest, est...","[restaurant, bar, restaurant]","[downtown madison, wisconsin, downtown madison...",43.074236,-89.381012,4.4,"[{'author_name': 'Sheri Mazariegos', 'author_u...",https://maps.google.com/?cid=11139728440618202797
3,The Harvey House,ChIJX9En6gZTBogREjWBvkYxbiM,"[restaurant, food, point_of_interest, establis...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.068292,-89.394975,4.7,"[{'author_name': 'Grace SHEN', 'author_url': '...",https://maps.google.com/?cid=2553032218679260434
4,Graze Restaurant,ChIJy_R_dz9TBogRz4rN3JmZd4o,"[bar, restaurant, food, point_of_interest, est...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.075138,-89.382232,4.4,"[{'author_name': 'Mike Udelhoven', 'author_url...",https://maps.google.com/?cid=9977612385576127183
...,...,...,...,...,...,...,...,...,...,...
262,Michael's Frozen Custard,ChIJKd0PLuNTBogRpbgwtLHf1TQ,"[restaurant, store, food, point_of_interest, e...",[fastfood],"[eastside madison, wisconsin]",43.085144,-89.325375,4.2,"[{'author_name': 'Nicholas Sinn', 'author_url'...",https://maps.google.com/?cid=3807195014336919717
263,Subway,ChIJTYtqQe1WBogRCs9UizX_GII,"[meal_takeaway, restaurant, food, point_of_int...",[fastfood],"[eastside madison, wisconsin]",43.125726,-89.305819,3.1,"[{'author_name': 'Delilah McKinney', 'author_u...",https://maps.google.com/?cid=9374523229807628042
264,Gotham Bagels,ChIJQRBusEBTBogRcy7R2nAaxlI,"[bakery, restaurant, store, food, point_of_int...",[fastfood],"[eastside madison, wisconsin]",43.076888,-89.383586,4.1,"[{'author_name': 'Dave Cameron', 'author_url':...",https://maps.google.com/?cid=5964483828508601971
265,Five Guys,ChIJ8w_QsvNWBogRLI2Ty99NJ94,"[meal_takeaway, restaurant, food, point_of_int...",[fastfood],"[eastside madison, wisconsin]",43.129030,-89.303904,4.1,"[{'author_name': 'Dean Krapf', 'author_url': '...",https://maps.google.com/?cid=16007849024100207916
266,Taco Bell,ChIJvYrMuYxWBogRgk6jw8mazO8,"[meal_takeaway, restaurant, food, point_of_int...",[fastfood],"[eastside madison, wisconsin]",43.125446,-89.312893,3.6,"[{'author_name': 'DK_Bemost55', 'author_url': ...",https://maps.google.com/?cid=17279356061675114114

In [202]:
def select_first_two_words(name):
    split_name = name.lower().split(' ')
    i = -1
    final_name = []
    while len(final_name) < 2:
        i += 1
        try:
            if split_name[i] == 'the' or split_name[i] == 'madison' or split_name[i] == '-':
                continue
            else:
                split_name[i] = split_name[i].replace(",", "").replace("’", "'").replace("à", "a").replace("è", "e")
                final_name.append(split_name[i])
        except IndexError:
            break
            
    final_name = " ".join(final_name)
    return final_name

df['shortened_name'] = df['name'].apply(select_first_two_words)
df.head()

,name,place_id,types,our_type,our_area,lat,long,avg_rating,reviews,url,shortened_name
0,The Botanist Social,ChIJgctqeEZTBogRzXAwmYqT1mk,"[restaurant, bar, food, point_of_interest, est...","[restaurant, bar, restaurant, bar, restaurant,...","[downtown madison, wisconsin, downtown madison...",43.074879,-89.388355,4.4,"[{'author_name': 'Pam Buss', 'author_url': 'ht...",https://maps.google.com/?cid=7626445242483372237,botanist social
1,The Stuffed Olive - Madison,ChIJF1eSTehTBogREHSPhHN1VIo,"[restaurant, food, point_of_interest, establis...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.074700,-89.391593,4.5,"[{'author_name': 'Denyse Nizam', 'author_url':...",https://maps.google.com/?cid=9967721014283432976,stuffed olive
2,Merchant Madison,ChIJ31Hrtz9TBogRrTZd9f5DmJo,"[bar, restaurant, food, point_of_interest, est...","[restaurant, bar, restaurant]","[downtown madison, wisconsin, downtown madison...",43.074236,-89.381012,4.4,"[{'author_name': 'Sheri Mazariegos', 'author_u...",https://maps.google.com/?cid=11139728440618202797,merchant
3,The Harvey House,ChIJX9En6gZTBogREjWBvkYxbiM,"[restaurant, food, point_of_interest, establis...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.068292,-89.394975,4.7,"[{'author_name': 'Grace SHEN', 'author_url': '...",https://maps.google.com/?cid=2553032218679260434,harvey house
4,Graze Restaurant,ChIJy_R_dz9TBogRz4rN3JmZd4o,"[bar, restaurant, food, point_of_interest, est...","[restaurant, restaurant, restaurant]","[downtown madison, wisconsin, westside madison...",43.075138,-89.382232,4.4,"[{'author_name': 'Mike Udelhoven', 'author_url...",https://maps.google.com/?cid=9977612385576127183,graze restaurant

In [204]:
df.to_csv('testing_reviews.csv')

In [119]:
testing_name = "Ian’s Pizza Madison"

testing_name.replace("’", "'").replace("à", "a").replace("è", "e")

"Ian's Pizza Madison"

In [200]:
test_name = "ian's pizza"
test_review1 = """Quick, Delicious, and Friendly
Ian's Pizza definitely delivered! I tried the vegetarian with potato and a classic cheese slice. The crust was perfect, and the toppings were fresh and flavorful.
Quick service and staff was also super friendly and accommodating.
Overall, a great experience! I'll definitely be back to try more of their menu."""
test_review2 = """Ian's was at Gamehole Con this year.  I got the Buffalo Chicken pizza at their booth, and after I got it, it slid off my plate on the floor.  The wonderful people at Ian's did not hesitate and made me a new slice no charge.  And the pizza was fabulous on top of it!
"""
test_review3 = "i love ians"

split_test_name = test_name.split(" ")

# cleaned_review = ""

# check for each word
def censor_review(place_name, review):
    cleaned_review = ""

    # censor common swear words
    profanity.load_censor_words()
    cleaned_review = profanity.censor(review)

    # in reviews we have read today, we've seen these words commonly used in a negative connotation
    custom_swear_list = ['hispanic', 'black', 'latino', 'english', 'spanish', 'asian']
    profanity.add_censor_words(custom_swear_list)
    if profanity.contains_profanity(cleaned_review):
        # completely remove review if it is derogatory
        return None
    
    for word in place_name.split(" "):
        search_string = "(?i)" + word
        if cleaned_review == "":
            cleaned_review = re.sub(search_string, '*****', review)
        else:
            cleaned_review = re.sub(search_string, '*****', cleaned_review)
        word = word.replace("'", "").replace(".", "").replace("\n", "")
        search_string = "(?i)" + word
        cleaned_review = re.sub(search_string, '*****', cleaned_review)
    return cleaned_review
    
    # check for both words
    # search_string = r"(?i)"
    # for word in split_test_name:
    #     search_string += word + r'\s*'
    # cleaned_review = re.sub(search_string, ' ***** ', cleaned_review)

censor_review("bagels forever", 'ians pizza was so good')

'ians pizza was so good'

In [196]:
# df

In [203]:
def clean_reviews(row):
    for review in row['reviews']:
        cleaned_review_list = []
        cleaned_review = {
            'rating': review['rating'],
            'text': censor_review(row['shortened_name'], review['text'])
        }
        cleaned_review_list.append(cleaned_review)

    return [cleaned_review_list]

df['cleaned_reviews'] = df.apply(clean_reviews, axis = 1)

In [ ]:
df.to_file()

,name,place_id,types,our_type,our_area,lat,long,geometry,avg_rating,reviews,url,shortened_name,cleaned_reviews
0,The Botanist Social,ChIJgctqeEZTBogRzXAwmYqT1mk,"[restaurant, bar, food, point_of_interest, est...","[restaurant, bar]","[downtown madison, wisconsin, downtown madison...",43.074879,-89.388355,[POINT (43.0748792 -89.3883548)],4.4,"[{'author_name': 'Pam Buss', 'author_url': 'ht...",https://maps.google.com/?cid=7626445242483372237,botanist social,"[[{'rating': 5, 'text': 'Loved The ***** *****..."
1,The Stuffed Olive - Madison,ChIJF1eSTehTBogREHSPhHN1VIo,"[restaurant, food, point_of_interest, establis...",[restaurant],"[downtown madison, wisconsin]",43.074700,-89.391593,[POINT (43.0746997 -89.3915933)],4.5,"[{'author_name': 'Denyse Nizam', 'author_url':...",https://maps.google.com/?cid=9967721014283432976,stuffed olive,"[[{'rating': 3, 'text': None}]]"
2,Heritage Tavern,ChIJfbNZvEBTBogRuJb-FBB3R0c,"[restaurant, food, point_of_interest, establis...",[restaurant],"[downtown madison, wisconsin]",43.076836,-89.383252,[POINT (43.0768359 -89.3832525)],4.6,"[{'author_name': 'Matt Morio', 'author_url': '...",https://maps.google.com/?cid=5136204810994751160,heritage tavern,"[[{'rating': 5, 'text': 'Have been here before..."
3,Merchant Madison,ChIJ31Hrtz9TBogRrTZd9f5DmJo,"[bar, restaurant, food, point_of_interest, est...","[restaurant, bar]","[downtown madison, wisconsin, downtown madison...",43.074236,-89.381012,[POINT (43.0742365 -89.38101189999999)],4.4,"[{'author_name': 'Sheri Mazariegos', 'author_u...",https://maps.google.com/?cid=11139728440618202797,merchant,"[[{'rating': 3, 'text': 'Took the family tonig..."
4,The Harvey House,ChIJX9En6gZTBogREjWBvkYxbiM,"[restaurant, food, point_of_interest, establis...",[restaurant],"[downtown madison, wisconsin]",43.068292,-89.394975,[POINT (43.068292 -89.3949751)],4.7,"[{'author_name': 'Grace SHEN', 'author_url': '...",https://maps.google.com/?cid=2553032218679260434,harvey house,"[[{'rating': 5, 'text': 'Hidden excellence! H..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Butterbird,ChIJW6_KXKmtB4gRDX4RtDWa3-Q,"[restaurant, food, point_of_interest, establis...",[fastfood],"[downtown madison, wisconsin]",43.067830,-89.405562,[POINT (43.06783 -89.40556210000001)],4.4,"[{'author_name': 'Gino Ricchio', 'author_url':...",https://maps.google.com/?cid=16492069915899035149,butterbird,"[[{'rating': 4, 'text': 'The atmosphere in her..."
145,Subway,ChIJ1SlsazZTBogRpdDpI71Y8po,"[meal_takeaway, restaurant, food, point_of_int...",[fastfood],"[downtown madison, wisconsin]",43.073251,-89.383596,[POINT (43.0732509 -89.38359609999999)],3.6,"[{'author_name': 'Simon Poldi', 'author_url': ...",https://maps.google.com/?cid=11165083995579469989,subway,"[[{'rating': 1, 'text': 'ordered on door dash,..."
146,Jimmy John's,ChIJWaRxasWsB4gRID6nn0RGscA,"[restaurant, food, point_of_interest, establis...",[fastfood],"[downtown madison, wisconsin]",43.068034,-89.408793,[POINT (43.0680341 -89.4087933)],3.6,"[{'author_name': 'Steve McConnell', 'author_ur...",https://maps.google.com/?cid=13884956386710208032,jimmy john's,"[[{'rating': 5, 'text': 'Xen is genuinely the ..."
147,Cousins Subs,ChIJFXAAGzGtB4gR_9NzKTYUgGo,"[restaurant, food, point_of_interest, establis...",[fastfood],"[downtown madison, wisconsin]",43.067777,-89.400683,[POINT (43.06777719999999 -89.4006833)],3.7,"[{'author_name': 'Gwen McCutcheon', 'author_ur...",https://maps.google.com/?cid=7674155987895571455,cousins subs,"[[{'rating': 1, 'text': 'Just received my sub ..."
148,QDOBA Mexican Eats,ChIJu1oDoM2sB4gRe_cq14K_2YY,"[bar, store, restaurant, food, point_of_intere...",[fastfood],"[downtown madison, wisconsin]",43.067863,-89.401237,[POINT (43.067863 -89.4012371)],4.1,"[{'author_name': 'Bani', 'author_url': 'https:...",https://maps.google.com/?cid=9717008239705126779,qdoba mexican,"[[{'rating': 1, 'text': 'I usually enjoy *****..."