In [23]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [103]:
import googlemaps
import os
import pandas as pd
from dotenv import load_dotenv
from fuzzywuzzy import fuzz
import numpy as np
import regex as re
import json
import ast

In [5]:
maps_client = googlemaps.Client(key = os.getenv('google_maps_api_key'))

In [19]:
mcdonalds = maps_client.places("McDonalds, Madison")
mcdonalds = maps_client.place('ChIJs-aLQc6sB4gRFe2Zx4HReSM', fields=['reviews'])

In [20]:
mcdonalds

{'html_attributions': [],
 'result': {'reviews': [{'author_name': 'Emmanuel Fernandez',
    'author_url': 'https://www.google.com/maps/contrib/115778137543745412555/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjX6IlZB7oQ3jQkNTyqQOSURtp99NVSq9gjMO6-qRDNWl4C_q7c=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': '3 months ago',
    'text': '(Drive-thru – 13 Nov 2025, ~5:30 AM)\nThe window attendant this morning was confrontational and extremely unprofessional. He said his name was Brandon, though I’m not sure that’s accurate. He’s a short Hispanic male who wears a blue button-up shirt and is usually stationed at the front counter or pick-up window.\n\nI normally give service workers the benefit of the doubt—they’re often overworked and underpaid—but this individual has been consistently rude in past visits and has also gotten my orders wrong before due to what seems like a lack of care.\n\nToday I ordered two sausage, egg, and cheese McGriddles. I was given two McGriddles without cheese. Simple mistakes happen, and I wasn’t upset about that. The problem was how he handled it. When I asked if the order could be corrected, he became aggressive, confrontational and insisted it was my fault. He even claimed he had repeated the order back to me when I ordered—something he absolutely did not do. I come to this location often, and when this employee is on drive-thru, the only thing he ever says is “what else” in a dismissive tone, often forgetting items and acting annoyed.\n\nThis employee needs proper customer-service training.',
    'time': 1763039532,
    'translated': False},
   {'author_name': 'Jaelinn Caroon',
    'author_url': 'https://www.google.com/maps/contrib/102290666342673075248/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjUJNTctfQu-eek3XuiaGzSq2wv9FOXWlT6AqG8e9YV7y6fI5o_D=s128-c0x00000000-cc-rp-mo-ba3',
    'rating': 2,
    'relative_time_description': '3 months ago',
    'text': "I get it. I've worked in fast food before. There's short staffing, poor pay and work conditions. And I don't completely understand McDonald's priority order system. But I order ONE item on the kiosk... About 15 minutes go by... NOTHING. Some older gentleman goes up to the front, gets a significant amount of food, and gets it all before mine. It wasn't even that busy, for a McDonald's at this location, plus there was a manager (I think) there, so you'd think it'd go faster. Food was alright, and the smaller older woman who was mopping the floors is amazing too. You get bonus points for her.",
    'time': 1762135032,
    'translated': False},
   {'author_name': 'Morgan Buchanan',
    'author_url': 'https://www.google.com/maps/contrib/100368394160100573127/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocIfi4JMlXVXzWS1NkysZzYpdRm2FuBDCzSDHDXYaEfbWsaOtA=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': 'a week ago',
    'text': 'When I pulled up to the drive thru, I was asked immediately what I wanted four times in a span of less than ninety seconds. It was rude, I asked to look at the menu, and they asked again. Impatient and unreasonable service, uncalled for rudeness when they extraneously added a side of mayo to the menu board. I’ve worked drive thru. The impatience drove me away from this business and it was so unnecessary.',
    'time': 1770499173,
    'translated': False},
   {'author_name': 'Jessica Tec Cob',
    'author_url': 'https://www.google.com/maps/contrib/105086313805536168060/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjVkCXF5mOHlFoEWbj3nbxMo8Ngs3g6egq6u8NY7manm7sfSOZRo=s128-c0x00000000-cc-rp-mo-ba2',
    'rating': 3,
    'relative_time_description': '2 months ago',
    'text': 'The sign says "try the grinch meal" and they don\'t have the grinch meal. The McDonald\'s on Park St has never failed me like this. I went to the McDonald\'s on Park st after this shit. They were nice enough to refund my money when I cancelled my order so you can have two extra stars.',
    'time': 1765528164,
    'translated': False},
   {'author_name': 'Eshan Ahmed',
    'author_url': 'https://www.google.com/maps/contrib/109871303240301440769/reviews',
    'language': 'en',
    'original_language': 'en',
    'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjX5LydGVkSQkiLz0kNz1n7GLFJ9quNdAGJDdUgWwL0vXdtabelF=s128-c0x00000000-cc-rp-mo',
    'rating': 1,
    'relative_time_description': '3 months ago',
    'text': 'worst fast food place I’ve ever been to by far. food takes too lobg to get prepared, unsanitary dining area, most of the kiosks dont work, the food doesn’t taste the best… the list goes on. every time I have gone, there has been problems. for some reason the people at the register either speak only Spanish or call out the wrong number. they also always forget to give you the sauce and the drinks that you pay for.',
    'time': 1763699017,
    'translated': False}]},
 'status': 'OK'}

In [22]:
review = "This Taco Bell is the most disgusting place I have ever laid my eyes on. It takes an exhaustive effort to lift your feet off of the floors. I felt like a mouse stuck on a glue trap. I have been here a few times and it's always terrible. The soda machines have never been cleaned and never will be cleaned. I am not kidding when I say that you can taste the mold or whatever other nastiness is in the soda machine and nozzles. Anyone who has worked in this type of industry knows that these machines need to be cleaned every night and deep cleaned every week, if you order a soda from here you will notice that it tastes almost like burnt hair. Just so incredibly disgusting it's unbelievable really. You cannot order at the counter, but they have kiosks. I use the mobile app and consistently what happens is my food is ready just sitting there and I can see it and it always takes them several minutes to simply just hand it to me. This most recent time I waited a very long time for my food to be ready and then it sat for a couple of minutes so I went up to kindly ask the worker if my order was ready, knowing that it was, and he just did not interact with me at all. he was 2 feet in front of me and just looking down a little bit and he looked extremely high, and had large open sores on his face. I don't think someone with open sores on their face should be working around food at all. I cant believe he was allowed to work in that condition. I did not even eat my food after seeing this I just threw it away. I think I have a moral obligation to call the health department to inspect this place and shut it down."

In [38]:
fuzz.partial_ratio("tacobell", "".join(review.lower().split()))
"tacobell" in "".join(review.lower().split())

True

In [ ]:
re.sub("(?i)taco\s*bell", "*****", review)

'sksdkjf*****'

In [ ]:
review_df = pd.read_csv("testing_reviews.csv")

,author_name,author_url,language,original_language,profile_photo_url,rating,relative_time_description,text,time,translated
0,Pam Buss,https://www.google.com/maps/contrib/1078297758...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIP-9...,5,a month ago,Went here with 2 others prior to a show at Ove...,1768070029,False
1,Shruti A,https://www.google.com/maps/contrib/1000255682...,en,en,https://lh3.googleusercontent.com/a/ACg8ocK5Cx...,5,a month ago,We really wanted to try this place and ended u...,1767727612,False
2,Kate Stephan,https://www.google.com/maps/contrib/1151953395...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjXQZ...,5,a week ago,The service here is amazing. They’re so knowle...,1770513420,False
3,Karyl Kubiak,https://www.google.com/maps/contrib/1073783970...,en,en,https://lh3.googleusercontent.com/a/ACg8ocK7IY...,5,a week ago,My husband and I had a wonderful time here bef...,1770512220,False
4,Sarah K,https://www.google.com/maps/contrib/1053924132...,en,en,https://lh3.googleusercontent.com/a/ACg8ocJJBl...,5,4 months ago,Loved The Botanist Social! We were seated righ...,1759074440,False

In [106]:
reviews_list = ast.literal_eval(review_df["reviews"][0])['reviews']

In [ ]:
for review in reviews_list:
    print(review)

{'author_name': 'Pam Buss', 'author_url': 'https://www.google.com/maps/contrib/107829775833265139536/reviews', 'language': 'en', 'original_language': 'en', 'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocIP-9GkylFlK3ZHN7Lsd2TQqboeCSSxDghC_cxCSyMcPsqvjA=s128-c0x00000000-cc-rp-mo-ba5', 'rating': 5, 'relative_time_description': 'a month ago', 'text': 'Went here with 2 others prior to a show at Overture. We had a reservation and were  immediately seated.\nThe restaurant is long and narrow with the bar taking up one side. Very nice atmosphere. We each had a speciality drink; painkiller, clover club, and proprietary knowledge.\nCheese curd appetizer which was yummy.\nEntrees included the lobster roll with truffle fries, shrimp risotto special and campanelle pasta. All our food was outstanding.\nService was excellent.\nI recommend checking this place out.', 'time': 1768070029, 'translated': False}
{'author_name': 'Shruti A', 'author_url': 'https://www.google.com/maps/contrib/100025568217789315713/reviews', 'language': 'en', 'original_language': 'en', 'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocK5CxdIlI0zzUHFLWCbVlSVETljbHns3EhQWqF03WaVEirZjw=s128-c0x00000000-cc-rp-mo-ba3', 'rating': 5, 'relative_time_description': 'a month ago', 'text': 'We really wanted to try this place and ended up coming with our two kids, even though it’s not especially kid-centric. The staff was incredibly accommodating—while there’s no kids menu, our waitress suggested great kid-friendly options and modifications from the regular menu. The drinks were amazing, the food was delicious, and we were seated right away with our reservation. Overall, a great experience—perfect for cocktails or hanging out with friends, and the crème brûlée was my favorite .', 'time': 1767727612, 'translated': False}
{'author_name': 'Kate Stephan', 'author_url': 'https://www.google.com/maps/contrib/115195339529880216927/reviews', 'language': 'en', 'original_language': 'en', 'profile_photo_url': 'https://lh3.googleusercontent.com/a-/ALV-UjXQZZ75gQ5HDTM9Z70OnfB32-X5-etjiBc3uVS7qWftC-8d8p6s=s128-c0x00000000-cc-rp-mo-ba2', 'rating': 5, 'relative_time_description': 'a week ago', 'text': 'The service here is amazing. They’re so knowledgeable and the fact that they have the drink ingredients memorized blows my mind. Alnea helped us and went above and beyond! I can’t wait to come back ♥️ The atmosphere is unmatched and the food is top notch. We came in and the hostess let us know they were full but had a lively spot at the standing area. Got drinks immediately and were happy. Come in and support local 💃🏻', 'time': 1770513420, 'translated': False}
{'author_name': 'Karyl Kubiak', 'author_url': 'https://www.google.com/maps/contrib/107378397062004991966/reviews', 'language': 'en', 'original_language': 'en', 'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocK7IY7hX4WQVDJILTRNQmIvSPRAykbGgTKdazyHRaRRNcWDdQ=s128-c0x00000000-cc-rp-mo', 'rating': 5, 'relative_time_description': 'a week ago', 'text': 'My husband and I had a wonderful time here before a show at the Overture. Alina made us delicious drinks, a yummy shot, and the real candles at the bar made for a relaxing vibe. Will definitely be back!', 'time': 1770512220, 'translated': False}
{'author_name': 'Sarah K', 'author_url': 'https://www.google.com/maps/contrib/105392413268606459498/reviews', 'language': 'en', 'original_language': 'en', 'profile_photo_url': 'https://lh3.googleusercontent.com/a/ACg8ocJJBlPFFg1WhNb1N_L0UiIyZZlvb_gBp3SLiiqqeciKuSc5_Q=s128-c0x00000000-cc-rp-mo', 'rating': 5, 'relative_time_description': '4 months ago', 'text': 'Loved The Botanist Social! We were seated right away on a busy Saturday night downtown. Great food, even better vibes. Risotto, fabulous. Patatas Bravas, phenomenal. Went a little crazy and had a little brownie with ice cream, delicious. Treat yourself.', 'time': 1759074440, 'translated': False}

In [154]:
botanist = pd.DataFrame(reviews_list)

In [ ]:
botanist[(botanist['rating'] == 5) | (botanist['rating'] == 4)]

,author_name,author_url,language,original_language,profile_photo_url,rating,relative_time_description,text,time,translated
0,Pam Buss,https://www.google.com/maps/contrib/1078297758...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIP-9...,5,a month ago,Went here with 2 others prior to a show at Ove...,1768070029,False
1,Shruti A,https://www.google.com/maps/contrib/1000255682...,en,en,https://lh3.googleusercontent.com/a/ACg8ocK5Cx...,5,a month ago,We really wanted to try this place and ended u...,1767727612,False
2,Kate Stephan,https://www.google.com/maps/contrib/1151953395...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjXQZ...,5,a week ago,The service here is amazing. They’re so knowle...,1770513420,False
3,Karyl Kubiak,https://www.google.com/maps/contrib/1073783970...,en,en,https://lh3.googleusercontent.com/a/ACg8ocK7IY...,5,a week ago,My husband and I had a wonderful time here bef...,1770512220,False
4,Sarah K,https://www.google.com/maps/contrib/1053924132...,en,en,https://lh3.googleusercontent.com/a/ACg8ocJJBl...,5,4 months ago,Loved The Botanist Social! We were seated righ...,1759074440,False

In [ ]:
botanist[(botanist['rating'] == 1) | (botanist['rating'] == 2)]

In [185]:
def reviews_to_dict(row):
    # print(row)
    reviews = pd.DataFrame(ast.literal_eval(row['reviews'])['reviews'])
    # print(reviews)
    return reviews.iloc[0]

review_df.apply(reviews_to_dict, axis=1)

,author_name,author_url,language,original_language,profile_photo_url,rating,relative_time_description,text,time,translated
0,Pam Buss,https://www.google.com/maps/contrib/1078297758...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIP-9...,5,a month ago,Went here with 2 others prior to a show at Ove...,1768070029,False
1,Denyse Nizam,https://www.google.com/maps/contrib/1005305109...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjU-V...,5,4 months ago,Very classy vibe with amazing martinis🍸and gre...,1760881180,False
2,Jerry Murphy,https://www.google.com/maps/contrib/1182817190...,en,en,https://lh3.googleusercontent.com/a/ACg8ocI8C1...,4,3 months ago,We had three pieces of pizza and soda and the ...,1763407287,False
3,Tambra Riddle,https://www.google.com/maps/contrib/1133683813...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjV5p...,5,4 months ago,I was so happy to discover this new place! It ...,1759698352,False
4,Cortney Forman,https://www.google.com/maps/contrib/1063860961...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIJub...,5,a week ago,"Placed my first order today through the ""goodi...",1771046624,False
5,Danica Odyssey,https://www.google.com/maps/contrib/1023361162...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjVeS...,5,3 months ago,"After a chilly, but fun day in Madison, I coul...",1761420586,False
6,chad svastisalee,https://www.google.com/maps/contrib/1057183292...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjWeS...,4,3 months ago,State Street Brats deals are a great way to en...,1763898156,False
7,Dave McGowan,https://www.google.com/maps/contrib/1162310295...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjU5S...,5,3 months ago,"Hot spicy fried noodles, under $8 and incredib...",1762735337,False
8,Chris,https://www.google.com/maps/contrib/1027406638...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUIR...,5,4 months ago,I was led here by a coupon for a free gyro and...,1760564662,False
9,Emmanuel Martinez,https://www.google.com/maps/contrib/1001451363...,en,en,https://lh3.googleusercontent.com/a/ACg8ocKz65...,2,2 weeks ago,"Be careful if you're vegetarian, it's the seco...",1770479803,False
10,Jason C,https://www.google.com/maps/contrib/1088603245...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjX7w...,5,7 months ago,"Super delicious, quick spot to grab a healthy ...",1752381142,False
11,MrsOlatubi,https://www.google.com/maps/contrib/1086237267...,en,en,https://lh3.googleusercontent.com/a/ACg8ocKemC...,4,2 months ago,A quaint Bohemian designed cafe in the middle ...,1764074910,False
12,reuben fendt,https://www.google.com/maps/contrib/1173528252...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIAtt...,5,a week ago,A focal point of downtown Madison dining. Exce...,1770603407,False
13,Rachel,https://www.google.com/maps/contrib/1135480728...,en,en,https://lh3.googleusercontent.com/a/ACg8ocIrRA...,5,a month ago,"The best margarita!!! Shrimp taco was good, to...",1768799356,False
14,Robert Demelo,https://www.google.com/maps/contrib/1111307875...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjWNh...,4,a month ago,Happened to be in Madison and heard Ian’s was ...,1768966621,False
15,Alex Torea,https://www.google.com/maps/contrib/1170088191...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjVhT...,5,2 months ago,The food is so so good! Warming and delicious....,1765999045,False
16,Ahmed BenGhatnsh,https://www.google.com/maps/contrib/1090762226...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjVsh...,2,5 months ago,I ordered from door dash this is my review.\nI...,1756867349,False
17,Che-Wei Hsu,https://www.google.com/maps/contrib/1146635480...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUNk...,5,2 months ago,The Indulgent BBQ is the best choice here!\nSu...,1766338396,False
18,Stephanie Varilek,https://www.google.com/maps/contrib/1155302838...,en,en,https://lh3.googleusercontent.com/a/ACg8ocLgVE...,4,2 weeks ago,"Food was prepared well, and flavors were fanta...",1769905403,False
19,Heather Li,https://www.google.com/maps/contrib/1083823912...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUfT...,4,8 months ago,"I love Potbelly's Mediterranean sandwich, and ...",1748785670,False
20,Yajun Hao,https://www.google.com/maps/contrib/1153345654...,en,en,https://lh3.googleusercontent.com/a/ACg8ocI0OX...,5,6 months ago,Love SGD Korean restaurant! The tofu soup is f...,1753558962,False
21,The Prussian Queen,https://www.google.com/maps/contrib/1008807233...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUdj...,5,3 months ago,Love coming here and this was my first time or...,1762471092,False
22,Darin K,https://www.google.com/maps/contrib/1111108171...,en,en,https://lh3.googleusercontent.com/a/ACg8ocJ4ws...,1,3 months ago,Shady place. Came from about 5 hours away to ...,1761762501,False
23,Anthony Ladd,https://www.google.com/maps/contrib/1155329150...,en,en,https://lh3.googleusercontent.com/a/ACg8ocICly...,5,8 months ago,Walked over after visiting MMOCA for dinner. N...,1750028641,False
24,Angie Ford,https://www.google.com/maps/contrib/1023003155...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjVUS...,5,3 weeks ago,Took our daughter to celebrate her birthday. E...,1769302056,False
25,Patrick Dunlop,https://www.google.com/maps/contrib/1009151865...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUoY...,5,4 months ago,"Small place, big food! Stopped in looking for ...",1759175327,False
26,elise mirabella,https://www.google.com/maps/contrib/1060010508...,en,en,https://lh3.googleusercontent.com/a/ACg8ocKxE-...,5,3 weeks ago,My husband and I wanted to grab a quick bite t...,1769371112,False
27,Ashley Sinnorai,https://www.google.com/maps/contrib/1055655279...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjW3A...,4,2 years ago,I originally wanted to eat at Rising Son Lao &...,1705464678,False
28,The Connonedrum,https://www.google.com/maps/contrib/1175687710...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjVF7...,5,a month ago,I went to Justveggiez with my wife and the foo...,1767211259,False
29,Ella Silver,https://www.google.com/maps/contrib/1093422917...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjWBX...,5,2 weeks ago,"Michelangelo’s is great any time of day, any d...",1769919152,False
30,Nigal Gahtham,https://www.google.com/maps/contrib/1045934985...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjX0l...,5,5 months ago,Showed up at opening time and food was cooked ...,1758492138,False
31,K Tania,https://www.google.com/maps/contrib/1107927501...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjViE...,5,a year ago,The owner is the person who really likes to co...,1713626610,False
32,Christopher Martin,https://www.google.com/maps/contrib/1144540295...,en,en,https://lh3.googleusercontent.com/a/ACg8ocLU-r...,5,5 months ago,I have been there a couple of times and I can ...,1756173442,False
33,Adeline Golatke,https://www.google.com/maps/contrib/1120125389...,en,en,https://lh3.googleusercontent.com/a/ACg8ocLvMg...,1,a month ago,"Ordered the sesame chicken to go, it was dry a...",1767239207,False
34,Jake Dubs,https://www.google.com/maps/contrib/1011046303...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjWTL...,1,a month ago,I ordered a 5 pack of frozen beef with the wor...,1768773477,False
35,Neeraj Mishra,https://www.google.com/maps/contrib/1167221778...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjV5Y...,5,3 weeks ago,"This bowl was absolutely delicious. Rich, spic...",1769482763,False
36,Rez Behnam,https://www.google.com/maps/contrib/1043929696...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjXpy...,4,3 weeks ago,Lots of poke places in Madison. This is a rea...,1769648771,False
37,Eric Randall,https://www.google.com/maps/contrib/1094069770...,en,en,https://lh3.googleusercontent.com/a/ACg8ocI3hf...,1,a month ago,I tried to order by phone for a pick up it wen...,1768786739,False
38,Pakou Lo,https://www.google.com/maps/contrib/1143069285...,en,en,https://lh3.googleusercontent.com/a/ACg8ocI9MC...,5,7 months ago,We stopped here after a show. So glad we did! ...,1753401150,False
39,The Boys,https://www.google.com/maps/contrib/1082432234...,en,en,https://lh3.googleusercontent.com/a-/ALV-UjUGP...,5,10 months ago,The Dollar Oysters deal is fantastic. 10/10 wo...,1744164375,False